name: Check PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: brulex/linters/actions/npm-cache@master

  prettier:
    name: Prettier check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: brulex/linters/actions/npm-cache@master

      - name: Run prettier
        run: npm run prettier

  tests:
    name: Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: brulex/linters/actions/npm-cache@master

      - name: Run prettier
        run: npm run test

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: brulex/linters/actions/npm-cache@master

      - name: Run build
        run: npm run build
